import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Login } from '../components/login'

export default function Home() {
  return (
    <>
    
    <Head>
        <title>HOWDY - TCC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login>
      </Login>

    </>
     
  )
}
